### ISSUE TITLE
git rebase master gh-pages

### ISSUE THREAD

**Issue by bortkiewicz** [Ways-to-not-make-money/wtnmm-javascript#1]

**Comment by bortkiewicz** [comment]
We need this to include the game in the actual website.

**Comment by bortkiewicz** [comment]
I'm trying to say, should I do this?

**Comment by hanyuone** [comment]
Yeah, I was figuring out a way to do this, I just didn't have enough time to post the issue. We should do this.

**Comment by hanyuone** [comment]
Also, a few issues:
- Auto-compiling CoffeeScript in browser - can you figure out a way to do this?
- Can you, if possible, also style up the whole game a bit using CSS?

Side note: was the idea of grouping all of the buildings and upgrades into lists a good idea?

**Comment by bortkiewicz** [comment]
Right now I'm busy moving everything to the .github.io repo.

**Comment by hanyuone** [comment]
Cool cool. After you finish moving all the files, can you make the webpage look more beautiful? Thanks.
